apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: app
    instance: "app-v2"
    version: "v2"
spec:
  containers:
    - name: app
      image: app:2.0
      ports:
        - name: http-port
          containerPort: 80
          protocol: TCP
      resources:
        requests:
          memory: 256Mi
          cpu: "100m"
        limits:
          memory: 1Gi
          cpu: "300m"
      livenessProbe:
        httpGet:
          path: /healthz
          port: http-port
  initContainers:
    - name: init-app
      image: init-app:1.0
